/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/demo/ag-grid/': RouteRecordInfo<'/demo/ag-grid/', '/demo/ag-grid', Record<never, never>, Record<never, never>>,
    'Better Scroll': RouteRecordInfo<'Better Scroll', '/demo/better-scroll', Record<never, never>, Record<never, never>>,
    'Codemirror6': RouteRecordInfo<'Codemirror6', '/demo/codemirror', Record<never, never>, Record<never, never>>,
    '状态机图': RouteRecordInfo<'状态机图', '/demo/flow', Record<never, never>, Record<never, never>>,
    '/demo/flow/NodeScript': RouteRecordInfo<'/demo/flow/NodeScript', '/demo/flow/NodeScript', Record<never, never>, Record<never, never>>,
    '鼠标框选元素': RouteRecordInfo<'鼠标框选元素', '/demo/range-selection', Record<never, never>, Record<never, never>>,
    '简单的右键菜单': RouteRecordInfo<'简单的右键菜单', '/draft/PlainContextmenu', Record<never, never>, Record<never, never>>,
    '/js/binary-search': RouteRecordInfo<'/js/binary-search', '/js/binary-search', Record<never, never>, Record<never, never>>,
    '/js/build-tree-01': RouteRecordInfo<'/js/build-tree-01', '/js/build-tree-01', Record<never, never>, Record<never, never>>,
    '/js/generate-tree': RouteRecordInfo<'/js/generate-tree', '/js/generate-tree', Record<never, never>, Record<never, never>>,
    '/js/hash-01': RouteRecordInfo<'/js/hash-01', '/js/hash-01', Record<never, never>, Record<never, never>>,
    '/js/number-format': RouteRecordInfo<'/js/number-format', '/js/number-format', Record<never, never>, Record<never, never>>,
    '/leet/alternating-subarray': RouteRecordInfo<'/leet/alternating-subarray', '/leet/alternating-subarray', Record<never, never>, Record<never, never>>,
    '/leet/merge': RouteRecordInfo<'/leet/merge', '/leet/merge', Record<never, never>, Record<never, never>>,
    'Randow Walker': RouteRecordInfo<'Randow Walker', '/nature/c01-walker', Record<never, never>, Record<never, never>>,
    'Randow Walker With Noise': RouteRecordInfo<'Randow Walker With Noise', '/nature/c02-walker-noise', Record<never, never>, Record<never, never>>,
    'Vector 01': RouteRecordInfo<'Vector 01', '/nature/c03-vector', Record<never, never>, Record<never, never>>,
    'Vector 01': RouteRecordInfo<'Vector 01', '/nature/c04-vector', Record<never, never>, Record<never, never>>,
    '/rx/': RouteRecordInfo<'/rx/', '/rx', Record<never, never>, Record<never, never>>,
    '/rx/d-01': RouteRecordInfo<'/rx/d-01', '/rx/d-01', Record<never, never>, Record<never, never>>,
    '/svg/path-01': RouteRecordInfo<'/svg/path-01', '/svg/path-01', Record<never, never>, Record<never, never>>,
    '/tmp/math-01': RouteRecordInfo<'/tmp/math-01', '/tmp/math-01', Record<never, never>, Record<never, never>>,
    '/ui/blog01/': RouteRecordInfo<'/ui/blog01/', '/ui/blog01', Record<never, never>, Record<never, never>>,
  }
}
